name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip <<EOF
          cd ~/webxr-3d-viewer
          git pull origin main
          conda activate webxr3d-env
          pip install -r requirements.txt
          # Restart your application process
          pkill -f "python app.py"
          nohup python app.py &
        EOF